# Generated by Django 5.2.7 on 2025-10-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción del Producto')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría del Producto')),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('stockMinimo', models.IntegerField(verbose_name='Stock Mínimo')),
                ('stockActual', models.IntegerField(verbose_name='Stock Actual')),
            ],
        ),
    ]
