# Generated by Django 5.2.7 on 2025-11-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JDATV1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=100, verbose_name='Nombre de Usuario')),
                ('apellidoUsuario', models.CharField(max_length=100, verbose_name='Apellido de Usuario')),
                ('contrasena', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('rol', models.CharField(max_length=50, verbose_name='Rol del Usuario')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
            ],
        ),
    ]
