# Generated by Django 5.2.7 on 2025-11-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JDATV1', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Lacteos', 'Lacteos'), ('Embutidos', 'Embutidos'), ('Salsas', 'Salsas'), ('Bebidas', 'Bebidas')], max_length=100, verbose_name='Categoría del Producto'),
        ),
    ]
