# Generated by Django 5.2.7 on 2025-11-24 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JDATV1', '0005_remove_usuario_contrasena_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Correo'),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('idMovimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad/Stock')),
                ('idDetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JDATV1.producto', verbose_name='Producto afectado')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realiza el movimiento')),
            ],
        ),
    ]
